### ISSUE TITLE
How to start bot 

### ISSUE THREAD

**Issue by Prasadnaw** [zhon12345/Ticket-Bot#11]

**Comment by Prasadnaw** [comment]
![Screenshot 2021-08-01 201800](https://user-images.githubusercontent.com/79042630/127775205-06ffdad5-a5dc-4c1b-80b1-24102003507a.png)
![Screenshot 2021-08-01 201833](https://user-images.githubusercontent.com/79042630/127775222-f89485e0-394c-4728-a9c2-ad5452e0e335.png)

**Comment by zhon12345** [comment]
How about NOT using JavaScript Debugger

**Comment by Prasadnaw** [comment]
Can you please explain me in detail as I am a student Learning In standard 8TH And Know some coding as I am learning it now.
