### ISSUE TITLE
how to setup support role id

### ISSUE THREAD

**Issue by Gamelegendx** [zhon12345/Ticket-Bot#13]

**Comment by zhon12345** [comment]
Please describe/give an example to your question, I simple do not understand what you mean by "how to setup support role id"

**Comment by Gamelegendx** [comment]
> Please describe/give an example to your question, I simple do not understand what you mean by "how to setup support role id"

bro i mean members who have support role can see the ticket and and please add claim and a ticket emebed message like when we create a ticket with reaction then after in ticket it first ask what is your issue then the player reply and then it embeded theat asnwer

**Comment by zhon12345** [comment]
> members who have support role can see the ticket

If you want to know how to let other roles see the ticket then refer to [this](https://github.com/zhon12345/Ticket-Bot/issues/14#issuecomment-897309190) issue.  

> please add claim

wdym add claim?

> when we create a ticket with reaction

Huh? since when does my code creates ticket when someone reacts to a reaction?
