### ISSUE TITLE
Permissions to view the ticket

### ISSUE THREAD

**Issue by YannLyy** [zhon12345/Ticket-Bot#14]
From what I have seen, I have searched, but no way to set the permission that can see the tickets at their opening.

For the moment, it's only the people with the "ADMINISTRATOR" permission who can see the tickets...

**Comment by zhon12345** [comment]
By default, "ADMINISTRATOR" permission lets the user access every channel. If you want other roles to access the tickets learn how to use `permissionOverwrites`, I'm using it in [news.js](https://github.com/zhon12345/Ticket-Bot/blob/main/commands/ticket/new.js) to deny 'VIEW_CHANNEL' permission to the members with the `everyone` role.

https://discord.js.org/#/docs/main/12.5.3/class/PermissionOverwrites
