### ISSUE TITLE
Problem Ticket-Bot

### ISSUE THREAD

**Issue by XianPT** [zhon12345/Ticket-Bot#35]
I will be trying to start the Bot in question, and it says that its prefix is ​​not defined. 
After that I can't use the prefix I put in the example.env file

https://cdn.discordapp.com/attachments/971446807857098773/1033778079337824336/unknown.png

After

https://prnt.sc/-IbJXToje8gS

**Comment by zhon12345** [comment]
Have you renamed your env file from `example.env` to `.env`
