### ISSUE TITLE
Launching eror 

### ISSUE THREAD

**Issue by VynzzDev** [zhon12345/Ticket-Bot#36]
![IMG-20230104-WA0011](https://user-images.githubusercontent.com/114085678/210489059-7cdaf07c-4369-49ed-8430-ea9c059752fe.jpg)

**Comment by zhon12345** [comment]
If you're getting this error, thats means you **DO NOT** have Privileged Intents enabled.
```Privileged intent provided is not enabled or whitelisted.```

**1.** Go to <https://discord.com/developers> and click on your bot application.
**2.** Click on the "Bot" tab on the left sidebar.
**3.** Scroll down until you see **Privileged Gateway Intents** 
**4.** Enable the two features according to the picture below.

https://i.imgur.com/WfBLtXY.png
